-- ============================================================================
-- SUPPLEMENT to 20260409235959_final.sql  (v2 - Complete)
-- Created: 2026-04-10
--
-- ⚠️  RUN ORDER:
--   STEP 1: Run 20260409235959_final.sql   (all public schema: tables, functions, RLS, grants)
--   STEP 2: Run THIS FILE                  (missing items not exported in Supabase snapshot)
--
-- WHY THIS FILE EXISTS:
--   The _final.sql was generated by Supabase's schema export tool which:
--   (a) Only exports the "public" schema — misses auth.* triggers
--   (b) Captures public schema at a point where some items were NOT YET backfilled
--   (c) Does NOT export the "storage" schema (buckets + RLS policies)
--
-- WHAT IS MISSING (identified by cross-checking all 33 migration files):
--   1.  sources.uploaded_by column
--   2.  on_auth_user_created trigger on auth.users   ← CRITICAL
--   3.  Storage: 3 buckets (sources, audio, public-images) + all RLS policies
--
-- ============================================================================


-- ============================================================================
-- 1. MISSING COLUMN: sources.uploaded_by
-- ============================================================================
-- The _final.sql CREATE TABLE "public"."sources" omits this column.
-- However, the live database DOES have it (confirmed via Supabase MCP).
-- It was added during development but the snapshot was taken before backfill.
--
-- Source migrations:
--   20260402050000_fix_source_triggers_use_invoker.sql (referenced in comments)
-- The column is NOT actively used by triggers anymore (reverted to auth.uid()),
-- but it must exist because the Supabase DB has it and app code may reference it.

ALTER TABLE public.sources
  ADD COLUMN IF NOT EXISTS uploaded_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;


-- ============================================================================
-- 2. MISSING TRIGGER: on_auth_user_created  ← CRITICAL - DO NOT SKIP
-- ============================================================================
-- Supabase schema export only exports "public" schema objects.
-- This trigger fires on the "auth" schema and is NEVER included in exports.
--
-- IMPACT: Without this trigger, new user signups will NOT create a profile row.
-- ALL RLS policies check public.profiles.role — without a profile, every
-- authenticated user will be denied access to every table in the database.
--
-- Source: 20260325172400_v0.2_optimized.sql

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ============================================================================
-- 3. MISSING: Storage Buckets
-- ============================================================================
-- Supabase schema export NEVER exports the storage schema.
-- All three buckets used by the project must be created manually.
--
-- Sources:
--   20260325172400_v0.2_optimized.sql       — initial bucket creation
--   20260325224200_storage_size_limit.sql   — sources size set to 25MB
--   20260330160000_fix_sharing_security.sql  — final bucket config with correct MIME types
--
-- FINAL STATE after all migrations:
--   sources:       private, 26,214,400 bytes (25MB), pdf/text/audio
--   audio:         private, 104,857,600 bytes (100MB), audio only
--   public-images: public,  10,485,760  bytes (10MB), images only

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  (
    'sources',
    'sources',
    false,          -- private
    26214400,       -- 25 MB (migration 20260325224200 overrides the 50MB default)
    ARRAY[
      'application/pdf',
      'text/plain',
      'text/csv',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'audio/mpeg',
      'audio/wav',
      'audio/mp4',
      'audio/m4a'
    ]
  ),
  (
    'audio',
    'audio',
    false,          -- private
    104857600,      -- 100 MB
    ARRAY[
      'audio/mpeg',
      'audio/wav',
      'audio/mp4',
      'audio/m4a'
    ]
  ),
  (
    'public-images',
    'public-images',
    true,           -- public
    10485760,       -- 10 MB
    ARRAY[
      'image/jpeg',
      'image/png',
      'image/gif',
      'image/webp',
      'image/svg+xml'
    ]
  )
ON CONFLICT (id) DO UPDATE SET
  file_size_limit    = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types,
  public             = EXCLUDED.public;


-- ============================================================================
-- 4. MISSING: Storage RLS Policies — sources bucket
-- ============================================================================
-- FINAL STATE after all migrations (chain: v0.2 → fix_sharing_security → fix_editor_viewer_roles)
--
-- The earlier per-user policies ("Users can view/upload/delete their own files")
-- were all REPLACED by role-based policies ("Members can...") in
-- migration 20260330160000_fix_sharing_security.sql, then the delete policy
-- was updated again in 20260330170000_fix_editor_viewer_roles.sql.

-- Clean up any old per-user policies that may exist from earlier migrations
DROP POLICY IF EXISTS "Users can view their own source files"                              ON storage.objects;
DROP POLICY IF EXISTS "Users can upload source files to their notebooks"                   ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload to sources bucket"                   ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload to sources bucket with size limit"   ON storage.objects;
DROP POLICY IF EXISTS "Users can update their own source files"                            ON storage.objects;
DROP POLICY IF EXISTS "Users can delete their own source files"                            ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can read their own files"                       ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can delete their own files"                     ON storage.objects;
DROP POLICY IF EXISTS "Owners can delete source files"                                     ON storage.objects;

-- SELECT: Any notebook member (owner/editor/viewer) can download source files
DROP POLICY IF EXISTS "Members can view source files" ON storage.objects;
CREATE POLICY "Members can view source files"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'sources'
    AND (SELECT public.get_notebook_role((storage.foldername(name))[1]::uuid)) IS NOT NULL
  );

-- INSERT: Only owner and editor can upload source files
DROP POLICY IF EXISTS "Members can upload source files" ON storage.objects;
CREATE POLICY "Members can upload source files"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'sources'
    AND (SELECT public.get_notebook_role((storage.foldername(name))[1]::uuid)) IN ('owner', 'editor')
  );

-- UPDATE: Only owner and editor can update source file metadata
DROP POLICY IF EXISTS "Members can update source files" ON storage.objects;
CREATE POLICY "Members can update source files"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'sources'
    AND (SELECT public.get_notebook_role((storage.foldername(name))[1]::uuid)) IN ('owner', 'editor')
  );

-- DELETE: Owner OR editor can delete source files
-- (updated in 20260330170000_fix_editor_viewer_roles.sql — editors were given delete access)
DROP POLICY IF EXISTS "Members can delete source files" ON storage.objects;
CREATE POLICY "Members can delete source files"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'sources'
    AND (SELECT public.get_notebook_role((storage.foldername(name))[1]::uuid)) IN ('owner', 'editor')
  );


-- ============================================================================
-- 5. MISSING: Storage RLS Policies — audio bucket
-- ============================================================================
-- Audio files (podcast overviews) — stored in the 'audio' bucket.
-- Final RLS from 20260330170000_fix_editor_viewer_roles.sql.

DROP POLICY IF EXISTS "Users can view their own audio files"    ON storage.objects;
DROP POLICY IF EXISTS "Service role can manage audio files"     ON storage.objects;
DROP POLICY IF EXISTS "Users can delete their own audio files"  ON storage.objects;
DROP POLICY IF EXISTS "Owners can delete audio files"           ON storage.objects;

-- SELECT: Any notebook member can play/download audio
DROP POLICY IF EXISTS "Members can view audio files" ON storage.objects;
CREATE POLICY "Members can view audio files"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'audio'
    AND (SELECT public.get_notebook_role((storage.foldername(name))[1]::uuid)) IS NOT NULL
  );

-- DELETE: Owner OR editor can delete audio files
-- (updated in 20260330170000_fix_editor_viewer_roles.sql)
DROP POLICY IF EXISTS "Members can delete audio files" ON storage.objects;
CREATE POLICY "Members can delete audio files"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'audio'
    AND (SELECT public.get_notebook_role((storage.foldername(name))[1]::uuid)) IN ('owner', 'editor')
  );

-- NOTE: audio INSERT/UPDATE are handled by the service_role (Edge Functions / n8n)
-- which bypasses RLS, so no INSERT/UPDATE policies are needed for authenticated role.


-- ============================================================================
-- 6. MISSING: Storage RLS Policies — public-images bucket
-- ============================================================================
-- Public images (e.g., notebook cover images, avatars) — public bucket.
-- Source: 20260325172400_v0.2_optimized.sql

DROP POLICY IF EXISTS "Anyone can view public images"         ON storage.objects;
DROP POLICY IF EXISTS "Service role can manage public images" ON storage.objects;

-- Anyone (including anon) can view images in the public bucket
CREATE POLICY "Anyone can view public images"
  ON storage.objects FOR SELECT
  TO anon, authenticated
  USING (bucket_id = 'public-images');

-- Only service_role can write to the public-images bucket (handled by Edge Functions)
-- No INSERT/UPDATE/DELETE policies for 'authenticated' role needed.


-- ============================================================================
-- 7. VERIFICATION NOTES
-- ============================================================================
-- After running both files, confirm the following are present:
--
-- Tables (9):
--   profiles, notebooks, sources, notes, documents,
--   notebook_members, activity_log, n8n_chat_histories, flowcharts
--
-- Functions (14):
--   handle_new_user, update_updated_at_column,
--   is_notebook_owner, is_notebook_owner_for_document,
--   match_documents, is_admin, get_notebook_role,
--   cleanup_notebook_chat_history, search_users, get_admin_users,
--   log_source_added, log_source_deleted, log_source_updated,
--   search_notebook_content
--
-- Triggers (10 active, 1 on auth schema):
--   update_profiles_updated_at          (profiles)
--   update_notebooks_updated_at         (notebooks)
--   update_sources_updated_at           (sources)
--   update_notes_updated_at             (notes)
--   update_notebook_members_updated_at  (notebook_members)
--   update_flowcharts_updated_at        (flowcharts)
--   cleanup_notebook_chat_history_trigger (notebooks)
--   trigger_log_source_added            (sources)
--   trigger_log_source_deleted          (sources)
--   trigger_log_source_updated          (sources)
--   on_auth_user_created                (auth.users) ← added by this file
--
-- NOTE: trigger_log_member_activity was created then DROPPED in migration
--   20260331000003_drop_member_trigger.sql — it should NOT exist.
--
-- RLS Policies (30 on public schema + storage):
--   profiles: profiles_select_policy, profiles_update_policy
--   notebooks: Notebook read/write/delete access, Users can create/view own notebooks
--   sources: Source read/write/update/delete access
--   notes: Private note read/write/update/delete access
--   documents: Document read/write/update/delete access
--   n8n_chat_histories: Chat history read/write/delete access
--   notebook_members: Notebook members visible, Only owner can invite/remove, Owner can update
--   activity_log: activity_log_select_members
--   flowcharts: Private flowchart read/write/update/delete access
--   storage.objects: Members can view/upload/update/delete source files,
--                    Members can view/delete audio files,
--                    Anyone can view public images
--
-- Storage Buckets (3):
--   sources (private, 25MB), audio (private, 100MB), public-images (public, 10MB)
